CatBoostClassifier:
  depth: 8
  iterations: 400
  learning_rate: 0.03549840551705406
  min_data_in_leaf: 10
  random_state: 1234
  verbose: 0
KNeighborsClassifier:
  algorithm: auto
  leaf_size: 30
  metric: minkowski
  metric_params: null
  n_jobs: null
  n_neighbors: 250
  p: 2
  weights: distance
LGBMClassifier:
  boosting_type: gbdt
  class_weight: null
  colsample_bytree: 1.0
  importance_type: split
  learning_rate: 0.032688144532186776
  max_depth: 6
  min_child_samples: 20
  min_child_weight: 0.001
  min_split_gain: 0.0
  n_estimators: 200
  n_jobs: null
  num_leaves: 31
  objective: null
  random_state: 1234
  reg_alpha: 0.1729449098405652
  reg_lambda: 0.18267460862048387
  subsample: 1.0
  subsample_for_bin: 200000
  subsample_freq: 0
  verbose: -1
LogisticRegression:
  C: 0.9983288808690397
  class_weight: null
  dual: false
  fit_intercept: true
  intercept_scaling: 1
  l1_ratio: null
  max_iter: 50
  multi_class: auto
  n_jobs: null
  penalty: l2
  random_state: 1234
  solver: newton-cholesky
  tol: 0.0001
  verbose: 0
  warm_start: false
RandomForestClassifier:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: null
  criterion: gini
  max_depth: 8
  max_features: sqrt
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 450
  n_jobs: null
  oob_score: false
  random_state: 1234
  verbose: 0
  warm_start: false
XGBClassifier:
  base_score: null
  booster: null
  callbacks: null
  colsample_bylevel: null
  colsample_bynode: null
  colsample_bytree: null
  device: null
  early_stopping_rounds: null
  enable_categorical: false
  eval_metric: null
  feature_types: null
  gamma: 0.37409629440984726
  grow_policy: null
  importance_type: null
  interaction_constraints: null
  learning_rate: 0.013725533621457658
  max_bin: null
  max_cat_threshold: null
  max_cat_to_onehot: null
  max_delta_step: null
  max_depth: 8
  max_leaves: null
  min_child_weight: null
  missing: .nan
  monotone_constraints: null
  multi_strategy: null
  n_estimators: 250
  n_jobs: null
  num_parallel_tree: null
  objective: binary:logistic
  random_state: 1234
  reg_alpha: 0.06186760910800691
  reg_lambda: 0.10498830679383846
  sampling_method: null
  scale_pos_weight: null
  subsample: null
  tree_method: null
  validate_parameters: null
  verbosity: null
hillclimb_weights:
  CatBoostClassifier: 0.48999999999999977
  KNeighborsClassifier: 0.11
  LGBMClassifier: 0.3999999999999998
